name: sysfoo-ci-pipeline
on:
  push:
    branches:
      - 'master'
jobs:
  sysfoo-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Welcome to sysfoo"
        
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: Test
        run: mvn test
        
      - name: Clean Package
        run: mvn clean
        
      - name: Package
        run: mvn package

      - name: View files
        run: ls -lrt target
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sysfoo
          path: target/**.war
